version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VK_API_TOKEN=${VK_API_TOKEN}
      - VK_API_VERSION=${VK_API_VERSION}
      - VK_API_SECRET=${VK_API_SECRET}
      - VK_API_CONFIRMATION=${VK_API_CONFIRMATION}
    ports:
      - "8080:8080"

  ngrok:
    image: ngrok/ngrok
    command: ["http", "app:8080"]
    depends_on:
      - app
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040" # ngrok web interface